import { useRef, useEffect, useState } from 'react'

function useReveal() {
  const ref = useRef(null)
  const [visible, setVisible] = useState(false)

  useEffect(() => {
    const el = ref.current
    if (!el) return
    const observer = new IntersectionObserver(
      ([entry]) => { if (entry.isIntersecting) { setVisible(true); observer.disconnect() } },
      { threshold: 0.15 }
    )
    observer.observe(el)
    return () => observer.disconnect()
  }, [])

  return [ref, visible]
}

function RevealBlock({ children, className = '' }) {
  const [ref, visible] = useReveal()
  return (
    <div
      ref={ref}
      className={className}
      style={{
        opacity: visible ? 1 : 0,
        transform: visible ? 'translateY(0)' : 'translateY(24px)',
        transition: 'opacity 0.5s ease-out, transform 0.5s ease-out',
      }}
    >
      {children}
    </div>
  )
}

export default function ProductExplainer() {
  return (
    <section className="relative py-24 sm:py-32 px-5" style={{ background: '#0B0D12' }}>

      {/* Section header */}
      <RevealBlock className="max-w-[720px] mx-auto text-center mb-20 sm:mb-28">
        <p style={{ fontFamily: "'IBM Plex Mono', monospace", fontSize: '12px', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.12em', color: '#2dd4bf', marginBottom: '16px' }}>
          Your Answers &mdash; Locked and Loaded
        </p>
        <h2 style={{ fontFamily: "'Outfit', sans-serif", fontSize: 'clamp(28px, 5vw, 44px)', fontWeight: 700, lineHeight: 1.15, letterSpacing: '-0.025em', color: '#f1f5f9' }}>
          Your Words. Your Stories.<br />On Screen Before You Need Them.
        </h2>
      </RevealBlock>

      {/* Block 1 — Quick Answers (left-weighted stat) */}
      <RevealBlock className="max-w-[820px] mx-auto mb-20 sm:mb-28">
        <div
          className="flex flex-col sm:flex-row gap-8 sm:gap-12 items-start"
          style={{ padding: '32px 28px', borderLeft: '2px solid rgba(45,212,191,0.2)', borderRadius: '0 12px 12px 0', background: 'rgba(17,24,37,0.4)' }}
        >
          {/* Stat */}
          <div className="shrink-0">
            <p style={{
              fontFamily: "'Outfit', sans-serif", fontSize: 'clamp(48px, 8vw, 64px)', fontWeight: 800,
              color: '#2dd4bf', lineHeight: 1, letterSpacing: '-0.03em',
              textShadow: '0 0 40px rgba(45,212,191,0.15)',
            }}>70%</p>
            <p style={{ fontFamily: "'IBM Plex Mono', monospace", fontSize: '12px', color: 'rgba(241,245,249,0.35)', marginTop: '8px', maxWidth: '180px', lineHeight: 1.5 }}>
              of interview questions are variations of the same 10 questions
            </p>
          </div>

          {/* Text */}
          <div>
            <h3 style={{ fontFamily: "'Outfit', sans-serif", fontSize: '22px', fontWeight: 700, color: '#f1f5f9', marginBottom: '12px', letterSpacing: '-0.015em' }}>
              One answer. Every time that question gets detected.
            </h3>
            <p style={{ fontSize: '15px', lineHeight: 1.7, color: 'rgba(241,245,249,0.5)' }}>
              Quick Answer cards let you prepare a single, sharp answer for each common question &mdash; written by you, generated by AI from your experience, or both. That card becomes YOUR answer. Locked in. The same structured, metrics-led response surfaces every time, across every round, across every process. No variation. No regeneration. No hoping the AI gives you something decent this time.
            </p>
          </div>
        </div>
      </RevealBlock>

      {/* Block 2 — AI Generation (centered, text-forward) */}
      <RevealBlock className="max-w-[520px] mx-auto mb-20 sm:mb-28 text-center">
        <div style={{ padding: '32px 24px' }}>
          {/* Badge */}
          <span style={{
            display: 'inline-block', fontFamily: "'IBM Plex Mono', monospace", fontSize: '11px', fontWeight: 600,
            textTransform: 'uppercase', letterSpacing: '0.1em', color: '#2dd4bf',
            background: 'rgba(45,212,191,0.08)', border: '1px solid rgba(45,212,191,0.15)',
            padding: '4px 14px', borderRadius: '20px', marginBottom: '20px',
          }}>
            The Other 30%
          </span>

          <h3 style={{ fontFamily: "'Outfit', sans-serif", fontSize: '24px', fontWeight: 700, color: '#f1f5f9', marginBottom: '16px', letterSpacing: '-0.015em' }}>
            Your experience. Their context. One answer.
          </h3>

          <p style={{ fontSize: '15px', lineHeight: 1.7, color: 'rgba(241,245,249,0.5)', textAlign: 'left', marginBottom: '16px' }}>
            For questions you didn&apos;t prep for &mdash; the curveball about your leadership style, the deep dive into a deal you didn&apos;t expect &mdash; the AI generates from your real material. Your resume, your deal history, your role context. But it goes further: it pulls from the job description, the company&apos;s market, the specific role &mdash; and weaves it in. When they ask how you&apos;d approach their mid-market segment, the answer connects your territory growth to THEIR territory, THEIR ICP, THEIR competitive landscape.
          </p>

          <p style={{ fontSize: '13px', lineHeight: 1.65, color: 'rgba(241,245,249,0.3)', textAlign: 'left' }}>
            Not a generic paragraph. A structured, metrics-led response formatted the way the question demands: STAR narrative, competitive reframe, territory strategy, methodology walkthrough.
          </p>
        </div>
      </RevealBlock>

      {/* Block 3 — Speed (right-weighted stat, mirrors Block 1) */}
      <RevealBlock className="max-w-[820px] mx-auto">
        <div
          className="flex flex-col sm:flex-row-reverse gap-8 sm:gap-12 items-start"
          style={{ padding: '28px 28px', borderRight: '2px solid rgba(241,245,249,0.1)', borderRadius: '12px 0 0 12px', background: 'rgba(17,24,37,0.3)' }}
        >
          {/* Stat */}
          <div className="shrink-0 sm:text-right">
            <p style={{
              fontFamily: "'Outfit', sans-serif", fontSize: 'clamp(48px, 8vw, 64px)', fontWeight: 800,
              color: '#f1f5f9', lineHeight: 1, letterSpacing: '-0.03em',
              textShadow: '0 0 40px rgba(241,245,249,0.06)',
            }}>1-3s</p>
            <p style={{ fontFamily: "'IBM Plex Mono', monospace", fontSize: '12px', color: 'rgba(241,245,249,0.35)', marginTop: '8px', lineHeight: 1.5 }}>
              AI generation time.<br />Quick Answers are instant.
            </p>
          </div>

          {/* Text */}
          <div>
            <h3 style={{ fontFamily: "'Outfit', sans-serif", fontSize: '22px', fontWeight: 700, color: '#f1f5f9', marginBottom: '12px', letterSpacing: '-0.015em' }}>
              Both hit the screen while the interviewer is still talking.
            </h3>
            <p style={{ fontSize: '15px', lineHeight: 1.7, color: 'rgba(241,245,249,0.5)' }}>
              Before the pause that costs you credibility. Your best answers aren&apos;t missing. They&apos;re just trapped in your head at the worst possible moment. Interview Coach gets them out.
            </p>
          </div>
        </div>
      </RevealBlock>

    </section>
  )
}
