import { useRef, useEffect, useState } from 'react'

function useReveal() {
  const ref = useRef(null)
  const [visible, setVisible] = useState(false)
  useEffect(() => {
    const el = ref.current
    if (!el) return
    const observer = new IntersectionObserver(
      ([entry]) => { if (entry.isIntersecting) { setVisible(true); observer.disconnect() } },
      { threshold: 0.15 }
    )
    observer.observe(el)
    return () => observer.disconnect()
  }, [])
  return [ref, visible]
}

function RevealBlock({ children, className = '', delay = 0 }) {
  const [ref, visible] = useReveal()
  return (
    <div ref={ref} className={className} style={{
      opacity: visible ? 1 : 0,
      transform: visible ? 'translateY(0)' : 'translateY(24px)',
      transition: `opacity 0.5s ease-out ${delay}ms, transform 0.5s ease-out ${delay}ms`,
    }}>
      {children}
    </div>
  )
}

const blocks = [
  {
    stat: '70%',
    statColor: '#2dd4bf',
    caption: 'of interview questions are variations of the same 10 questions.',
    headline: 'One answer. Every time that question gets detected.',
    body: 'Quick Answer cards let you prepare a single, sharp answer for each common question — written by you, generated by AI from your experience, or both. That card becomes YOUR answer. Locked in. The same structured, metrics-led response surfaces every time, across every round, across every process.',
    label: 'Quick Answers',
  },
  {
    stat: '30%',
    statColor: '#2dd4bf',
    caption: 'are questions you didn\u2019t prep for. The AI handles those.',
    headline: 'Your experience. Their context. One answer.',
    body: 'For the curveball about your leadership style or the deep dive into a deal you didn\u2019t expect — the AI generates from your real material. Your resume, your deal history, your role context. It pulls from the job description, the company\u2019s market, and the specific role — and weaves it all into a structured, metrics-led response.',
    label: 'AI Generation',
  },
  {
    stat: '1-3s',
    statColor: '#2dd4bf',
    caption: 'AI generation time. Quick Answers are instant.',
    headline: 'Both hit the screen while the interviewer is still talking.',
    body: 'Before the pause that costs you credibility. Your best answers aren\u2019t missing. They\u2019re just trapped in your head at the worst possible moment. Interview Coach gets them out.',
    label: 'Speed',
  },
]

export default function ProductExplainer() {
  return (
    <section className="relative py-24 sm:py-32 px-5" style={{ background: '#0B0D12' }}>

      {/* Section header */}
      <RevealBlock className="max-w-[720px] mx-auto text-center mb-16 sm:mb-24">
        <p style={{ fontFamily: "'IBM Plex Mono', monospace", fontSize: '12px', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.12em', color: '#2dd4bf', marginBottom: '16px' }}>
          Your Answers &mdash; Locked and Loaded
        </p>
        <h2 style={{ fontFamily: "'Outfit', sans-serif", fontSize: 'clamp(26px, 5vw, 42px)', fontWeight: 700, lineHeight: 1.15, letterSpacing: '-0.025em', color: '#f1f5f9' }}>
          Your Words. Your Stories.<br />On Screen Before You Need Them.
        </h2>
      </RevealBlock>

      {/* Three consistent blocks */}
      <div className="max-w-[720px] mx-auto flex flex-col gap-12 sm:gap-16">
        {blocks.map((block, i) => (
          <RevealBlock key={i} delay={i * 100}>
            <div style={{
              background: 'rgba(17,24,37,0.45)',
              border: '1px solid rgba(241,245,249,0.07)',
              borderRadius: '14px',
              padding: '28px 24px',
            }}>
              {/* Label — bold, teal */}
              <p style={{ fontFamily: "'Outfit', sans-serif", fontSize: '14px', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.06em', color: '#2dd4bf', marginBottom: '16px' }}>
                {block.label}
              </p>

              {/* Stat + caption — vertically centered */}
              <div className="flex items-center gap-5 mb-5">
                <p style={{
                  fontFamily: "'Outfit', sans-serif", fontSize: 'clamp(40px, 8vw, 56px)', fontWeight: 800,
                  color: block.statColor, lineHeight: 1, letterSpacing: '-0.03em', flexShrink: 0,
                  textShadow: block.statColor === '#2dd4bf' ? '0 0 40px rgba(45,212,191,0.12)' : '0 0 40px rgba(241,245,249,0.05)',
                }}>{block.stat}</p>
                <p style={{ fontSize: '14px', color: 'rgba(241,245,249,0.4)', lineHeight: 1.5, maxWidth: '280px' }}>
                  {block.caption}
                </p>
              </div>

              {/* Headline */}
              <h3 style={{ fontFamily: "'Outfit', sans-serif", fontSize: '20px', fontWeight: 700, color: '#f1f5f9', marginBottom: '10px', letterSpacing: '-0.015em' }}>
                {block.headline}
              </h3>

              {/* Body */}
              <p style={{ fontSize: '15px', lineHeight: 1.7, color: 'rgba(241,245,249,0.5)' }}>
                {block.body}
              </p>
            </div>
          </RevealBlock>
        ))}
      </div>

          {/* CTA */}
          <div className="text-center mt-12">
            <a href="#start" className="inline-block font-semibold transition-all duration-200"
              style={{ padding: '14px 32px', borderRadius: '10px', background: '#00E0CC', color: '#080B12', fontSize: '14px', textDecoration: 'none' }}>
              Start Your Free Practice Interview &rarr;
            </a>
          </div>

    </section>
  )
}
